openapi: 3.0.0
info:
  title: EpubPress - Read the web offline
  description: >-
    A browser extension for creating ebooks from your favorite webpages. Build
    books that are totally custom, offline and compatible with all your devices.
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api/v1'
    description: local development server
tags:
  - name: diagnostics
    description: helper endpoints
paths:
  /version:
    get:
      tags:
        - diagnostics
      responses:
        '200':
          description: version info
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                  minCompatible:
                    type: string
                  message:
                    type: string
                  clients:
                    type: array
                    items:
                      $ref: '#/components/schemas/ClientVersion'
components:
  schemas:
    ClientVersion:
      properties:
        minCompatible:
          type: string
        message:
          type: string
