# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build
on:
  push:
    branches: [master,publish-docker-image]
  pull_request:
    branches: [ master ]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
      - run: npm run lint
  publish:
    runs-on: ubuntu-latest
    needs: [test_and_lint]
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: haroldtreen/epub-press/server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
env:
  CI: true